AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  createPoll:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 20
      Role: 'arn:aws:iam::047149081783:role/service-role/createPoll-role-fa12sb88'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /poll
            Method: ANY
