AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  getPoll:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::047149081783:role/service-role/getPoll-role-041rtyct'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/poll/{pollID}'
            Method: ANY
